#!/bin/bash
set -e

GPBACKUP_BIN=/opt/greengagedb/gpbackup/bin

for gphome in /opt/greengagedb/greengage*/; do
    [ -d "${gphome}bin" ] || continue
    for binary in gpbackup gprestore gpbackup_helper; do
      ln -sf "${GPBACKUP_BIN}/${binary}" "${gphome}bin/${binary}"
    done
done
